описание
NewVegas3/java-filmorate pull request #4
Opened 2023-07-21 20:35 UTC by NewVegas3

2023-07-22 10:09 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/IdFilm.java
> +public abstract class IdFilm {
Хорошо что выделил в отдельный класс. Но т.к. используется не только для фильма но и для юзера, то назвать лучше например Identifier или Identified или Entity (все что имеет идентификатор принято называть сущьность, но это дальше будет проходится).

2023-07-22 10:11 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/validators/FilmsValidator.java
> +    public void validator(Film film) throws ObjectNotFoundException {
методы называем глаголом validate

2023-07-22 10:12 UTC, VadimZharkov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Класс ничего не делает, след-но зачем он

2023-07-22 10:16 UTC, VadimZharkov requested changes
У обоих контроллеров можно выделить общую логику в части работы с мапой и идентификаторами в базовый класс.

2023-07-22 13:10 UTC, NewVegas3 commented
Ну вроде все исправил, Класс идентификатор  переименовал на Entity  , переименовал метода на validate ,ну и удалил лишний FilmorateApplicationTests

2023-07-23 09:23 UTC, VadimZharkov approved these changes

2023-07-23 15:04 UTC, merged