добавлена вся необходимая новая логика и архитектура
NewVegas3/java-filmorate pull request #5
Opened 2023-08-06 14:01 UTC by NewVegas3

очень тяжко разобрался с дженериком и валидацией, но тесты прошли...

2023-08-07 06:25 UTC, VadimZharkov requested changes
Из ТЗ не очевидно, но как улучшение предлагаю следущее:
Реализовать так называемую слоистую архитектуру, где код разбивается на слои и каждый слой зависит только от соседнего с ним.
У нас можно выделить слой представления (rest api) - это классы контроллеров
слой бизнес-логики - это классы сервисов
и слой хранилища - это классы хранилищ
Схема их зависимостей и взаимодействия Контроллер->Сервис->Хранилище (т.е. контроллер с хранилищем напрямую не работатет)
Попробуй доработать в этом ключе (потребуется продублировать некоторые методы хранилищ в сервисах, но это неизбежное "зло" при делении на слои).

2023-08-07 06:35 UTC, NewVegas3 commented
> Из ТЗ не очевидно, но как продвигают следущее: Реализовать так называемую слоистую архитектуру, где код разбивается на слоях и каждый слой зависит только от соседнего с ним. У нас представлены слои представления (остальное API) - это классы контроллеров уровня бизнес-логики - это классы сервисов и складов хранилища - это классы хранилища Схема их зависимостей и взаимодействие Контроллер->Сервис->Хранилище (т.е. контроллер с хранилищем непосредственно не работает) Попробуй доработать в этом ключе (потребуется продублировать методы некоторых хранилищ в сервисах, но это неизбежное "зло" при делении на слоях).

Вы знаете что уже 5 раз читаю и  не совсем понимаю что именно нужно сделать (улучшить) ?
Можете пожалуйста подсказать более подробнее

2023-08-07 07:33 UTC, NewVegas3 commented
Про слоистую архитектуру не очень понял, но переделал логику теперь зависимость UserService в конструктор класса UserController. Каждый метод контроллера делегирует работу соответствующим методам в UserService.контроллеры (FilmController и UserController) зависят только от соответствующих сервисов (FilmService и UserService), а сервисы зависят только от хранилищ (InMemoryFilmStorage и InMemoryUserStorage).Ну или пытаются ))) во всяком случае тесты в Postman прошли

2023-08-08 05:07 UTC, VadimZharkov approved these changes

2023-08-08 05:10 UTC, VadimZharkov commented
> 

Работа была хорошая, поэтому подумал что можно пойти немного дальше) Про архитектуру в двух словах довольно трудно объяснить, со временем придет понимание). В целом все правильно.

2023-08-08 05:23 UTC, merged